package com.example.unieats.frontend.dashboard.admin.MenuManagement

data class MenuItemAdmin(
    var id: String = "",           // String to store the unique ID (generated by Firebase push or UUID)
    var name: String = "",        // Name of the menu item
    var category: String = "",    // Category of the menu item
    var price: Double = 0.0,      // Price of the menu item
    var quantity: Int = 0,        // Quantity of the menu item
    var imageUrl: String = ""     // URL of the image (after uploading to Firebase Storage)
)
